### PR TITLE
 Update for GHC 7.10.1, <$> is now in Prelude

### PR DESCRIPTION
**Pull request by alanz**

### CODE REVIEW

**Comment by achudnov** [comment]
Hi Alan,
The build fails in ghc 7.4: https://travis-ci.org/jswebtools/language-ecmascript/jobs/56741011. I guess it will require CPP to do neatly it neatly --- or update dependencies to preclude building on 7.4. I don't have time to figure that out right now. If you do, could you, please, update the PR accordingly? Also, I'm not able to test on GHC 7.10 as of yet.

**Comment by alanz** [comment]
I don't have travis configured on my repo, but it passes the tests on my box with GHC 7.10.1

**Comment by achudnov** [comment]
You can see the build failure via the link I've provided previously. But, basically ---and as expected--- the build fails on the versions of GHC where Prelude doesn't export the <$> operator you're trying to hide.

**Comment by alanz** [comment]
I meant it did not build in my fork, but did in yours, anc can now merge cleanly. See https://travis-ci.org/jswebtools/language-ecmascript/builds/56750945

**Comment by achudnov** [comment]
Oh I haven't noticed you've added another commit. Yeah, looks good: merging.

**Comment by achudnov** [comment]
Do you need this on Hackage soon?

**Comment by alanz** [comment]
When its convenient to you, I am building from my fork at the moment.

**Comment by bergmark** [comment]
wl-pprint doesn't build on 7.10 yet. https://github.com/haskell-infra/hackage-trustees/issues/14

**Comment by bergmark** [comment]
wl-pprint-1.2 has been released with GHC 7.10 support.

**Comment by achudnov** [comment]
Thanks, Adam! I can't test it with 7.10 right now as neither Travis CI, nor my dev machine have that version installed. Are you in a rush for 7.10 support?

**Comment by bergmark** [comment]
I don't need it since I have a fork on our private hackage, but this package is one of only three in the Silk dependency tree that aren't 7.10 compatible yet ;-)

**Comment by achudnov** [comment]
Fixed and released in 0.17.0.1

**Pull request merged**
