### PR TITLE
removed testing-feat depencancy from src, and tabs from Lexer

### PR DESCRIPTION
**Pull request by henrylaxen**
Best wishes,
Henry laxen

### CODE REVIEW

**Comment by henrylaxen** [comment]
Everything I wrote above got deleted just before I sent it, except the closing.  I'll rewrite it here.  I was trying to compile fay under ghc8.4.2 and cabal burped when it encountered a dependency on test-feat, which is required by ecmascript.  I took a look at your code and noticed that only your tests depended on test-feat, not the code itself, so I re-organized your cabal file to remove that dependency.  While I was at it I noticed some warnings about tabs in Parser.hs, so I fixed that too.  I hope this is helpful.

**Comment by henrylaxen** [comment]
I just noticed that I mistakenly modified the Cabal-Version to 1.10.0.1 instead of the Version field of the language-ecmascript.cabal file to 0.18.0.1.  Sorry.  If possible, could you push this to hackage.  It is really difficult to proceed with my fay pull request until it no longer explicitly depends on test-feat, which it only does because ecmascript does.  I'm trying to get fay running with ghc-8.4.2.  Thanks.

**Comment by henrylaxen** [comment]
Any chance of pushing this to hackage soon?

**Comment by achudnov** [comment]
Uploaded as 0.19 to Hackage. Thank you.

**Pull request merged**
